/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

#include "kernel_operator.h"
#include "activation/geglu.h"
#include "activation/gelu.h"
#include "activation/logsoftmax.h"
#include "activation/reglu.h"
#include "activation/sigmoid.h"
#include "activation/silu.h"
#include "activation/simplesoftmax.h"
#include "activation/softmax.h"
#include "activation/softmaxflashv2.h"
#include "activation/softmaxflashv3.h"
#include "activation/softmaxgrad.h"
#include "activation/swiglu.h"
#include "activation/swish.h"
#include "filter/dropout.h"
#include "hccl/hccl.h"
#include "hccl/hccl_common.h"
#include "hcomm/hcomm.h"
#include "index/arithprogression.h"
#include "kernel_struct_data_copy.h"
#include "math/acos.h"
#include "math/acosh.h"
#include "math/asin.h"
#include "math/asinh.h"
#include "math/atan.h"
#include "math/atanh.h"
#include "math/axpy.h"
#include "math/bitwise_and.h"
#include "math/bitwise_not.h"
#include "math/bitwise_or.h"
#include "math/bitwise_xor.h"
#include "math/ceil.h"
#include "math/clamp.h"
#include "math/cos.h"
#include "math/cosh.h"
#include "math/cumsum.h"
#include "math/digamma.h"
#include "math/erf.h"
#include "math/erfc.h"
#include "math/exp.h"
#include "math/floor.h"
#include "math/fma.h"
#include "math/fmod.h"
#include "math/frac.h"
#include "math/hypot.h"
#include "math/is_finite.h"
#include "math/is_inf.h"
#include "math/is_nan.h"
#include "math/lgamma.h"
#include "math/log.h"
#include "math/logical_and.h"
#include "math/logical_ands.h"
#include "math/logical_not.h"
#include "math/logical_or.h"
#include "math/logical_ors.h"
#include "math/logical_xor.h"
#include "math/philox.h"
#include "math/power.h"
#include "math/rint.h"
#include "math/round.h"
#include "math/sign.h"
#include "math/sin.h"
#include "math/sincos.h"
#include "math/sinh.h"
#include "math/tan.h"
#include "math/tanh.h"
#include "math/trunc.h"
#include "math/where.h"
#include "math/xor.h"
#include "normalization/batchnorm.h"
#include "normalization/deepnorm.h"
#include "normalization/groupnorm.h"
#include "normalization/layernorm.h"
#include "normalization/layernormgrad.h"
#include "normalization/layernormgradbeta.h"
#include "normalization/normalize.h"
#include "normalization/rmsnorm.h"
#include "normalization/welfordfinalize.h"
#include "pad/broadcast.h"
#include "pad/pad.h"
#include "quantization/antiquantize.h"
#include "quantization/ascend_antiquant.h"
#include "quantization/ascend_dequant.h"
#include "quantization/ascend_quant.h"
#include "quantization/dequantize.h"
#include "quantization/quantize.h"
#include "reduce/mean.h"
#include "reduce/reduce.h"
#include "reduce/reduce_xor_sum.h"
#include "reduce/sum.h"
#include "select/selectwithbytesmask.h"
#include "sort/sort.h"
#include "sort/topk.h"
#include "transpose/confusion_transpose.h"
#include "transpose/transdata.h"
#include "utils/init_global_memory.h"

using AscendC::Acos;
using AscendC::Acosh;
using AscendC::AdjustSoftMaxRes;
using AscendC::AntiQuantize;
using AscendC::Arange;
using AscendC::AscendAntiQuant;
using AscendC::AscendDequant;
using AscendC::AscendQuant;
using AscendC::Asin;
using AscendC::Asinh;
using AscendC::Atan;
using AscendC::Atanh;
using AscendC::Axpy;
using AscendC::BatchNorm;
using AscendC::BitwiseAnd;
using AscendC::BitwiseNot;
using AscendC::BitwiseOr;
using AscendC::BitwiseXor;
using AscendC::Broadcast;
using AscendC::Ceil;
using AscendC::Clamp;
using AscendC::ClampMax;
using AscendC::ClampMin;
using AscendC::Cos;
using AscendC::Cosh;
using AscendC::CumSum;
using AscendC::DeepNorm;
using AscendC::Dequantize;
using AscendC::Digamma;
using AscendC::DropOut;
using AscendC::Erf;
using AscendC::Erfc;
using AscendC::Exp;
using AscendC::FasterGelu;
using AscendC::FasterGeluV2;
using AscendC::Fill;
using AscendC::Floor;
using AscendC::Fma;
using AscendC::Fmod;
using AscendC::Frac;
using AscendC::GeGLU;
using AscendC::Gelu;
using AscendC::GroupNorm;
using AscendC::Hypot;
using AscendC::IsFinite;
using AscendC::IsInf;
using AscendC::IsNan;
using AscendC::LayerNorm;
using AscendC::LayerNormGrad;
using AscendC::LayerNormGradBeta;
using AscendC::Lgamma;
using AscendC::Log;
using AscendC::Log10;
using AscendC::Log2;
using AscendC::LogSoftMax;
using AscendC::LogicalAnd;
using AscendC::LogicalAnds;
using AscendC::LogicalNot;
using AscendC::LogicalOr;
using AscendC::LogicalOrs;
using AscendC::LogicalXor;
using AscendC::MakeLayout;
using AscendC::MakeShape;
using AscendC::MakeStride;
using AscendC::Mean;
using AscendC::Normalize;
using AscendC::Pad;
using AscendC::PhiloxRandom;
using AscendC::Power;
using AscendC::Quantize;
using AscendC::ReGlu;
using AscendC::ReduceAll;
using AscendC::ReduceAny;
using AscendC::ReduceMax;
using AscendC::ReduceMean;
using AscendC::ReduceMin;
using AscendC::ReduceProd;
using AscendC::ReduceSum;
using AscendC::ReduceXorSum;
using AscendC::Rint;
using AscendC::RmsNorm;
using AscendC::Round;
using AscendC::Select;
using AscendC::Sigmoid;
using AscendC::Sign;
using AscendC::Silu;
using AscendC::SimpleSoftMax;
using AscendC::Sin;
using AscendC::SinCos;
using AscendC::Sinh;
using AscendC::SoftMax;
using AscendC::SoftmaxFlashV2;
using AscendC::SoftmaxFlashV3;
using AscendC::SoftmaxGrad;
using AscendC::SoftmaxGradFront;
using AscendC::Sort;
using AscendC::Sum;
using AscendC::SwiGLU;
using AscendC::Swish;
using AscendC::Tan;
using AscendC::Tanh;
using AscendC::TopK;
using AscendC::TransData;
using AscendC::Transpose;
using AscendC::Trunc;
using AscendC::UnPad;
using AscendC::WelfordFinalize;
using AscendC::Where;
using AscendC::Xor;
